/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateWorkspaceRouteImport } from './routes/create-workspace'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceSlugRouteImport } from './routes/workspace/$slug'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoDbChatApiRouteImport } from './routes/demo/db-chat-api'
import { Route as DemoDbChatRouteImport } from './routes/demo/db-chat'
import { Route as WorkspaceSlugIndexRouteImport } from './routes/workspace/$slug/index'
import { Route as WorkspaceSlugTeamRouteImport } from './routes/workspace/$slug/team'
import { Route as WorkspaceSlugSettingsRouteImport } from './routes/workspace/$slug/settings'
import { Route as WorkspaceSlugCreateIssueRouteImport } from './routes/workspace/$slug/create-issue'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateWorkspaceRoute = CreateWorkspaceRouteImport.update({
  id: '/create-workspace',
  path: '/create-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugRoute = WorkspaceSlugRouteImport.update({
  id: '/workspace/$slug',
  path: '/workspace/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDbChatApiRoute = DemoDbChatApiRouteImport.update({
  id: '/demo/db-chat-api',
  path: '/demo/db-chat-api',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDbChatRoute = DemoDbChatRouteImport.update({
  id: '/demo/db-chat',
  path: '/demo/db-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugIndexRoute = WorkspaceSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugTeamRoute = WorkspaceSlugTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugSettingsRoute = WorkspaceSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugCreateIssueRoute =
  WorkspaceSlugCreateIssueRouteImport.update({
    id: '/create-issue',
    path: '/create-issue',
    getParentRoute: () => WorkspaceSlugRoute,
  } as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-workspace': typeof CreateWorkspaceRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/workspace/$slug': typeof WorkspaceSlugRouteWithChildren
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/workspace/$slug/create-issue': typeof WorkspaceSlugCreateIssueRoute
  '/workspace/$slug/settings': typeof WorkspaceSlugSettingsRoute
  '/workspace/$slug/team': typeof WorkspaceSlugTeamRoute
  '/workspace/$slug/': typeof WorkspaceSlugIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-workspace': typeof CreateWorkspaceRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/workspace/$slug/create-issue': typeof WorkspaceSlugCreateIssueRoute
  '/workspace/$slug/settings': typeof WorkspaceSlugSettingsRoute
  '/workspace/$slug/team': typeof WorkspaceSlugTeamRoute
  '/workspace/$slug': typeof WorkspaceSlugIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-workspace': typeof CreateWorkspaceRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/workspace/$slug': typeof WorkspaceSlugRouteWithChildren
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/workspace/$slug/create-issue': typeof WorkspaceSlugCreateIssueRoute
  '/workspace/$slug/settings': typeof WorkspaceSlugSettingsRoute
  '/workspace/$slug/team': typeof WorkspaceSlugTeamRoute
  '/workspace/$slug/': typeof WorkspaceSlugIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-workspace'
    | '/login'
    | '/signup'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/tanstack-query'
    | '/workspace/$slug'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/workspace/$slug/create-issue'
    | '/workspace/$slug/settings'
    | '/workspace/$slug/team'
    | '/workspace/$slug/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-workspace'
    | '/login'
    | '/signup'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/tanstack-query'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/workspace/$slug/create-issue'
    | '/workspace/$slug/settings'
    | '/workspace/$slug/team'
    | '/workspace/$slug'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/create-workspace'
    | '/login'
    | '/signup'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/tanstack-query'
    | '/workspace/$slug'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/workspace/$slug/create-issue'
    | '/workspace/$slug/settings'
    | '/workspace/$slug/team'
    | '/workspace/$slug/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateWorkspaceRoute: typeof CreateWorkspaceRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DemoDbChatRoute: typeof DemoDbChatRoute
  DemoDbChatApiRoute: typeof DemoDbChatApiRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  WorkspaceSlugRoute: typeof WorkspaceSlugRouteWithChildren
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-workspace': {
      id: '/create-workspace'
      path: '/create-workspace'
      fullPath: '/create-workspace'
      preLoaderRoute: typeof CreateWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$slug': {
      id: '/workspace/$slug'
      path: '/workspace/$slug'
      fullPath: '/workspace/$slug'
      preLoaderRoute: typeof WorkspaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/db-chat-api': {
      id: '/demo/db-chat-api'
      path: '/demo/db-chat-api'
      fullPath: '/demo/db-chat-api'
      preLoaderRoute: typeof DemoDbChatApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/db-chat': {
      id: '/demo/db-chat'
      path: '/demo/db-chat'
      fullPath: '/demo/db-chat'
      preLoaderRoute: typeof DemoDbChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$slug/': {
      id: '/workspace/$slug/'
      path: '/'
      fullPath: '/workspace/$slug/'
      preLoaderRoute: typeof WorkspaceSlugIndexRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/team': {
      id: '/workspace/$slug/team'
      path: '/team'
      fullPath: '/workspace/$slug/team'
      preLoaderRoute: typeof WorkspaceSlugTeamRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/settings': {
      id: '/workspace/$slug/settings'
      path: '/settings'
      fullPath: '/workspace/$slug/settings'
      preLoaderRoute: typeof WorkspaceSlugSettingsRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/create-issue': {
      id: '/workspace/$slug/create-issue'
      path: '/create-issue'
      fullPath: '/workspace/$slug/create-issue'
      preLoaderRoute: typeof WorkspaceSlugCreateIssueRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkspaceSlugRouteChildren {
  WorkspaceSlugCreateIssueRoute: typeof WorkspaceSlugCreateIssueRoute
  WorkspaceSlugSettingsRoute: typeof WorkspaceSlugSettingsRoute
  WorkspaceSlugTeamRoute: typeof WorkspaceSlugTeamRoute
  WorkspaceSlugIndexRoute: typeof WorkspaceSlugIndexRoute
}

const WorkspaceSlugRouteChildren: WorkspaceSlugRouteChildren = {
  WorkspaceSlugCreateIssueRoute: WorkspaceSlugCreateIssueRoute,
  WorkspaceSlugSettingsRoute: WorkspaceSlugSettingsRoute,
  WorkspaceSlugTeamRoute: WorkspaceSlugTeamRoute,
  WorkspaceSlugIndexRoute: WorkspaceSlugIndexRoute,
}

const WorkspaceSlugRouteWithChildren = WorkspaceSlugRoute._addFileChildren(
  WorkspaceSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateWorkspaceRoute: CreateWorkspaceRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DemoDbChatRoute: DemoDbChatRoute,
  DemoDbChatApiRoute: DemoDbChatApiRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  WorkspaceSlugRoute: WorkspaceSlugRouteWithChildren,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
