/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateWorkspaceRouteImport } from './routes/create-workspace'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceSlugRouteImport } from './routes/workspace/$slug'
import { Route as WorkspaceSlugIndexRouteImport } from './routes/workspace/$slug/index'
import { Route as WorkspaceSlugTeamRouteImport } from './routes/workspace/$slug/team'
import { Route as WorkspaceSlugSettingsRouteImport } from './routes/workspace/$slug/settings'
import { Route as WorkspaceSlugCreateIssueRouteImport } from './routes/workspace/$slug/create-issue'
import { Route as WorkspaceSlugProjectsIndexRouteImport } from './routes/workspace/$slug/projects/index'
import { Route as WorkspaceSlugCyclesIndexRouteImport } from './routes/workspace/$slug/cycles/index'
import { Route as WorkspaceSlugProjectsNewRouteImport } from './routes/workspace/$slug/projects/new'
import { Route as WorkspaceSlugProjectsProjectIdRouteImport } from './routes/workspace/$slug/projects/$projectId'
import { Route as WorkspaceSlugIssueIssueIdRouteImport } from './routes/workspace/$slug/issue/$issueId'
import { Route as WorkspaceSlugCyclesNewRouteImport } from './routes/workspace/$slug/cycles/new'
import { Route as WorkspaceSlugCyclesCycleIdRouteImport } from './routes/workspace/$slug/cycles/$cycleId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateWorkspaceRoute = CreateWorkspaceRouteImport.update({
  id: '/create-workspace',
  path: '/create-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugRoute = WorkspaceSlugRouteImport.update({
  id: '/workspace/$slug',
  path: '/workspace/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugIndexRoute = WorkspaceSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugTeamRoute = WorkspaceSlugTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugSettingsRoute = WorkspaceSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugCreateIssueRoute =
  WorkspaceSlugCreateIssueRouteImport.update({
    id: '/create-issue',
    path: '/create-issue',
    getParentRoute: () => WorkspaceSlugRoute,
  } as any)
const WorkspaceSlugProjectsIndexRoute =
  WorkspaceSlugProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => WorkspaceSlugRoute,
  } as any)
const WorkspaceSlugCyclesIndexRoute =
  WorkspaceSlugCyclesIndexRouteImport.update({
    id: '/cycles/',
    path: '/cycles/',
    getParentRoute: () => WorkspaceSlugRoute,
  } as any)
const WorkspaceSlugProjectsNewRoute =
  WorkspaceSlugProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => WorkspaceSlugRoute,
  } as any)
const WorkspaceSlugProjectsProjectIdRoute =
  WorkspaceSlugProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => WorkspaceSlugRoute,
  } as any)
const WorkspaceSlugIssueIssueIdRoute =
  WorkspaceSlugIssueIssueIdRouteImport.update({
    id: '/issue/$issueId',
    path: '/issue/$issueId',
    getParentRoute: () => WorkspaceSlugRoute,
  } as any)
const WorkspaceSlugCyclesNewRoute = WorkspaceSlugCyclesNewRouteImport.update({
  id: '/cycles/new',
  path: '/cycles/new',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugCyclesCycleIdRoute =
  WorkspaceSlugCyclesCycleIdRouteImport.update({
    id: '/cycles/$cycleId',
    path: '/cycles/$cycleId',
    getParentRoute: () => WorkspaceSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-workspace': typeof CreateWorkspaceRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace/$slug': typeof WorkspaceSlugRouteWithChildren
  '/workspace/$slug/create-issue': typeof WorkspaceSlugCreateIssueRoute
  '/workspace/$slug/settings': typeof WorkspaceSlugSettingsRoute
  '/workspace/$slug/team': typeof WorkspaceSlugTeamRoute
  '/workspace/$slug/': typeof WorkspaceSlugIndexRoute
  '/workspace/$slug/cycles/$cycleId': typeof WorkspaceSlugCyclesCycleIdRoute
  '/workspace/$slug/cycles/new': typeof WorkspaceSlugCyclesNewRoute
  '/workspace/$slug/issue/$issueId': typeof WorkspaceSlugIssueIssueIdRoute
  '/workspace/$slug/projects/$projectId': typeof WorkspaceSlugProjectsProjectIdRoute
  '/workspace/$slug/projects/new': typeof WorkspaceSlugProjectsNewRoute
  '/workspace/$slug/cycles/': typeof WorkspaceSlugCyclesIndexRoute
  '/workspace/$slug/projects/': typeof WorkspaceSlugProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-workspace': typeof CreateWorkspaceRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace/$slug/create-issue': typeof WorkspaceSlugCreateIssueRoute
  '/workspace/$slug/settings': typeof WorkspaceSlugSettingsRoute
  '/workspace/$slug/team': typeof WorkspaceSlugTeamRoute
  '/workspace/$slug': typeof WorkspaceSlugIndexRoute
  '/workspace/$slug/cycles/$cycleId': typeof WorkspaceSlugCyclesCycleIdRoute
  '/workspace/$slug/cycles/new': typeof WorkspaceSlugCyclesNewRoute
  '/workspace/$slug/issue/$issueId': typeof WorkspaceSlugIssueIssueIdRoute
  '/workspace/$slug/projects/$projectId': typeof WorkspaceSlugProjectsProjectIdRoute
  '/workspace/$slug/projects/new': typeof WorkspaceSlugProjectsNewRoute
  '/workspace/$slug/cycles': typeof WorkspaceSlugCyclesIndexRoute
  '/workspace/$slug/projects': typeof WorkspaceSlugProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-workspace': typeof CreateWorkspaceRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/workspace/$slug': typeof WorkspaceSlugRouteWithChildren
  '/workspace/$slug/create-issue': typeof WorkspaceSlugCreateIssueRoute
  '/workspace/$slug/settings': typeof WorkspaceSlugSettingsRoute
  '/workspace/$slug/team': typeof WorkspaceSlugTeamRoute
  '/workspace/$slug/': typeof WorkspaceSlugIndexRoute
  '/workspace/$slug/cycles/$cycleId': typeof WorkspaceSlugCyclesCycleIdRoute
  '/workspace/$slug/cycles/new': typeof WorkspaceSlugCyclesNewRoute
  '/workspace/$slug/issue/$issueId': typeof WorkspaceSlugIssueIssueIdRoute
  '/workspace/$slug/projects/$projectId': typeof WorkspaceSlugProjectsProjectIdRoute
  '/workspace/$slug/projects/new': typeof WorkspaceSlugProjectsNewRoute
  '/workspace/$slug/cycles/': typeof WorkspaceSlugCyclesIndexRoute
  '/workspace/$slug/projects/': typeof WorkspaceSlugProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-workspace'
    | '/login'
    | '/signup'
    | '/workspace/$slug'
    | '/workspace/$slug/create-issue'
    | '/workspace/$slug/settings'
    | '/workspace/$slug/team'
    | '/workspace/$slug/'
    | '/workspace/$slug/cycles/$cycleId'
    | '/workspace/$slug/cycles/new'
    | '/workspace/$slug/issue/$issueId'
    | '/workspace/$slug/projects/$projectId'
    | '/workspace/$slug/projects/new'
    | '/workspace/$slug/cycles/'
    | '/workspace/$slug/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-workspace'
    | '/login'
    | '/signup'
    | '/workspace/$slug/create-issue'
    | '/workspace/$slug/settings'
    | '/workspace/$slug/team'
    | '/workspace/$slug'
    | '/workspace/$slug/cycles/$cycleId'
    | '/workspace/$slug/cycles/new'
    | '/workspace/$slug/issue/$issueId'
    | '/workspace/$slug/projects/$projectId'
    | '/workspace/$slug/projects/new'
    | '/workspace/$slug/cycles'
    | '/workspace/$slug/projects'
  id:
    | '__root__'
    | '/'
    | '/create-workspace'
    | '/login'
    | '/signup'
    | '/workspace/$slug'
    | '/workspace/$slug/create-issue'
    | '/workspace/$slug/settings'
    | '/workspace/$slug/team'
    | '/workspace/$slug/'
    | '/workspace/$slug/cycles/$cycleId'
    | '/workspace/$slug/cycles/new'
    | '/workspace/$slug/issue/$issueId'
    | '/workspace/$slug/projects/$projectId'
    | '/workspace/$slug/projects/new'
    | '/workspace/$slug/cycles/'
    | '/workspace/$slug/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateWorkspaceRoute: typeof CreateWorkspaceRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  WorkspaceSlugRoute: typeof WorkspaceSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-workspace': {
      id: '/create-workspace'
      path: '/create-workspace'
      fullPath: '/create-workspace'
      preLoaderRoute: typeof CreateWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$slug': {
      id: '/workspace/$slug'
      path: '/workspace/$slug'
      fullPath: '/workspace/$slug'
      preLoaderRoute: typeof WorkspaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$slug/': {
      id: '/workspace/$slug/'
      path: '/'
      fullPath: '/workspace/$slug/'
      preLoaderRoute: typeof WorkspaceSlugIndexRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/team': {
      id: '/workspace/$slug/team'
      path: '/team'
      fullPath: '/workspace/$slug/team'
      preLoaderRoute: typeof WorkspaceSlugTeamRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/settings': {
      id: '/workspace/$slug/settings'
      path: '/settings'
      fullPath: '/workspace/$slug/settings'
      preLoaderRoute: typeof WorkspaceSlugSettingsRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/create-issue': {
      id: '/workspace/$slug/create-issue'
      path: '/create-issue'
      fullPath: '/workspace/$slug/create-issue'
      preLoaderRoute: typeof WorkspaceSlugCreateIssueRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/projects/': {
      id: '/workspace/$slug/projects/'
      path: '/projects'
      fullPath: '/workspace/$slug/projects/'
      preLoaderRoute: typeof WorkspaceSlugProjectsIndexRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/cycles/': {
      id: '/workspace/$slug/cycles/'
      path: '/cycles'
      fullPath: '/workspace/$slug/cycles/'
      preLoaderRoute: typeof WorkspaceSlugCyclesIndexRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/projects/new': {
      id: '/workspace/$slug/projects/new'
      path: '/projects/new'
      fullPath: '/workspace/$slug/projects/new'
      preLoaderRoute: typeof WorkspaceSlugProjectsNewRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/projects/$projectId': {
      id: '/workspace/$slug/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/workspace/$slug/projects/$projectId'
      preLoaderRoute: typeof WorkspaceSlugProjectsProjectIdRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/issue/$issueId': {
      id: '/workspace/$slug/issue/$issueId'
      path: '/issue/$issueId'
      fullPath: '/workspace/$slug/issue/$issueId'
      preLoaderRoute: typeof WorkspaceSlugIssueIssueIdRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/cycles/new': {
      id: '/workspace/$slug/cycles/new'
      path: '/cycles/new'
      fullPath: '/workspace/$slug/cycles/new'
      preLoaderRoute: typeof WorkspaceSlugCyclesNewRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/workspace/$slug/cycles/$cycleId': {
      id: '/workspace/$slug/cycles/$cycleId'
      path: '/cycles/$cycleId'
      fullPath: '/workspace/$slug/cycles/$cycleId'
      preLoaderRoute: typeof WorkspaceSlugCyclesCycleIdRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
  }
}

interface WorkspaceSlugRouteChildren {
  WorkspaceSlugCreateIssueRoute: typeof WorkspaceSlugCreateIssueRoute
  WorkspaceSlugSettingsRoute: typeof WorkspaceSlugSettingsRoute
  WorkspaceSlugTeamRoute: typeof WorkspaceSlugTeamRoute
  WorkspaceSlugIndexRoute: typeof WorkspaceSlugIndexRoute
  WorkspaceSlugCyclesCycleIdRoute: typeof WorkspaceSlugCyclesCycleIdRoute
  WorkspaceSlugCyclesNewRoute: typeof WorkspaceSlugCyclesNewRoute
  WorkspaceSlugIssueIssueIdRoute: typeof WorkspaceSlugIssueIssueIdRoute
  WorkspaceSlugProjectsProjectIdRoute: typeof WorkspaceSlugProjectsProjectIdRoute
  WorkspaceSlugProjectsNewRoute: typeof WorkspaceSlugProjectsNewRoute
  WorkspaceSlugCyclesIndexRoute: typeof WorkspaceSlugCyclesIndexRoute
  WorkspaceSlugProjectsIndexRoute: typeof WorkspaceSlugProjectsIndexRoute
}

const WorkspaceSlugRouteChildren: WorkspaceSlugRouteChildren = {
  WorkspaceSlugCreateIssueRoute: WorkspaceSlugCreateIssueRoute,
  WorkspaceSlugSettingsRoute: WorkspaceSlugSettingsRoute,
  WorkspaceSlugTeamRoute: WorkspaceSlugTeamRoute,
  WorkspaceSlugIndexRoute: WorkspaceSlugIndexRoute,
  WorkspaceSlugCyclesCycleIdRoute: WorkspaceSlugCyclesCycleIdRoute,
  WorkspaceSlugCyclesNewRoute: WorkspaceSlugCyclesNewRoute,
  WorkspaceSlugIssueIssueIdRoute: WorkspaceSlugIssueIssueIdRoute,
  WorkspaceSlugProjectsProjectIdRoute: WorkspaceSlugProjectsProjectIdRoute,
  WorkspaceSlugProjectsNewRoute: WorkspaceSlugProjectsNewRoute,
  WorkspaceSlugCyclesIndexRoute: WorkspaceSlugCyclesIndexRoute,
  WorkspaceSlugProjectsIndexRoute: WorkspaceSlugProjectsIndexRoute,
}

const WorkspaceSlugRouteWithChildren = WorkspaceSlugRoute._addFileChildren(
  WorkspaceSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateWorkspaceRoute: CreateWorkspaceRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  WorkspaceSlugRoute: WorkspaceSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
