/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateIssueRouteImport } from './routes/create-issue'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as CyclesIndexRouteImport } from './routes/cycles/index'
import { Route as WorkspaceSlugRouteImport } from './routes/workspace/$slug'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as IssueIssueIdRouteImport } from './routes/issue/$issueId'
import { Route as CyclesNewRouteImport } from './routes/cycles/new'
import { Route as CyclesCycleIdRouteImport } from './routes/cycles/$cycleId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIssueRoute = CreateIssueRouteImport.update({
  id: '/create-issue',
  path: '/create-issue',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const CyclesIndexRoute = CyclesIndexRouteImport.update({
  id: '/cycles/',
  path: '/cycles/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugRoute = WorkspaceSlugRouteImport.update({
  id: '/workspace/$slug',
  path: '/workspace/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const IssueIssueIdRoute = IssueIssueIdRouteImport.update({
  id: '/issue/$issueId',
  path: '/issue/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)
const CyclesNewRoute = CyclesNewRouteImport.update({
  id: '/cycles/new',
  path: '/cycles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CyclesCycleIdRoute = CyclesCycleIdRouteImport.update({
  id: '/cycles/$cycleId',
  path: '/cycles/$cycleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-issue': typeof CreateIssueRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/cycles/$cycleId': typeof CyclesCycleIdRoute
  '/cycles/new': typeof CyclesNewRoute
  '/issue/$issueId': typeof IssueIssueIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/workspace/$slug': typeof WorkspaceSlugRoute
  '/cycles/': typeof CyclesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-issue': typeof CreateIssueRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/cycles/$cycleId': typeof CyclesCycleIdRoute
  '/cycles/new': typeof CyclesNewRoute
  '/issue/$issueId': typeof IssueIssueIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/workspace/$slug': typeof WorkspaceSlugRoute
  '/cycles': typeof CyclesIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-issue': typeof CreateIssueRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/cycles/$cycleId': typeof CyclesCycleIdRoute
  '/cycles/new': typeof CyclesNewRoute
  '/issue/$issueId': typeof IssueIssueIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/workspace/$slug': typeof WorkspaceSlugRoute
  '/cycles/': typeof CyclesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-issue'
    | '/login'
    | '/settings'
    | '/signup'
    | '/cycles/$cycleId'
    | '/cycles/new'
    | '/issue/$issueId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/workspace/$slug'
    | '/cycles/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-issue'
    | '/login'
    | '/settings'
    | '/signup'
    | '/cycles/$cycleId'
    | '/cycles/new'
    | '/issue/$issueId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/workspace/$slug'
    | '/cycles'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/create-issue'
    | '/login'
    | '/settings'
    | '/signup'
    | '/cycles/$cycleId'
    | '/cycles/new'
    | '/issue/$issueId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/workspace/$slug'
    | '/cycles/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateIssueRoute: typeof CreateIssueRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  CyclesCycleIdRoute: typeof CyclesCycleIdRoute
  CyclesNewRoute: typeof CyclesNewRoute
  IssueIssueIdRoute: typeof IssueIssueIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  WorkspaceSlugRoute: typeof WorkspaceSlugRoute
  CyclesIndexRoute: typeof CyclesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-issue': {
      id: '/create-issue'
      path: '/create-issue'
      fullPath: '/create-issue'
      preLoaderRoute: typeof CreateIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycles/': {
      id: '/cycles/'
      path: '/cycles'
      fullPath: '/cycles/'
      preLoaderRoute: typeof CyclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$slug': {
      id: '/workspace/$slug'
      path: '/workspace/$slug'
      fullPath: '/workspace/$slug'
      preLoaderRoute: typeof WorkspaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issue/$issueId': {
      id: '/issue/$issueId'
      path: '/issue/$issueId'
      fullPath: '/issue/$issueId'
      preLoaderRoute: typeof IssueIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycles/new': {
      id: '/cycles/new'
      path: '/cycles/new'
      fullPath: '/cycles/new'
      preLoaderRoute: typeof CyclesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycles/$cycleId': {
      id: '/cycles/$cycleId'
      path: '/cycles/$cycleId'
      fullPath: '/cycles/$cycleId'
      preLoaderRoute: typeof CyclesCycleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateIssueRoute: CreateIssueRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  CyclesCycleIdRoute: CyclesCycleIdRoute,
  CyclesNewRoute: CyclesNewRoute,
  IssueIssueIdRoute: IssueIssueIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  WorkspaceSlugRoute: WorkspaceSlugRoute,
  CyclesIndexRoute: CyclesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
